/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { ApprovalControllerListPendingParams } from '../../schemas';

import { customInstance } from '../../axios-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List pending approvals
 */
export type approvalControllerListPendingResponse200 = {
  data: void;
  status: 200;
};

export type approvalControllerListPendingResponseSuccess =
  approvalControllerListPendingResponse200 & {
    headers: Headers;
  };
export type approvalControllerListPendingResponse = approvalControllerListPendingResponseSuccess;

export const getApprovalControllerListPendingUrl = (
  params?: ApprovalControllerListPendingParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/approvals?${stringifiedParams}` : `/approvals`;
};

export const approvalControllerListPending = async (
  params?: ApprovalControllerListPendingParams,
  options?: RequestInit
): Promise<approvalControllerListPendingResponse> => {
  return customInstance<approvalControllerListPendingResponse>(
    getApprovalControllerListPendingUrl(params),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getApprovalControllerListPendingQueryKey = (
  params?: ApprovalControllerListPendingParams
) => {
  return [`/approvals`, ...(params ? [params] : [])] as const;
};

export const getApprovalControllerListPendingQueryOptions = <
  TData = Awaited<ReturnType<typeof approvalControllerListPending>>,
  TError = unknown,
>(
  params?: ApprovalControllerListPendingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof approvalControllerListPending>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getApprovalControllerListPendingQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalControllerListPending>>> = ({
    signal,
  }) => approvalControllerListPending(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof approvalControllerListPending>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ApprovalControllerListPendingQueryResult = NonNullable<
  Awaited<ReturnType<typeof approvalControllerListPending>>
>;
export type ApprovalControllerListPendingQueryError = unknown;

export function useApprovalControllerListPending<
  TData = Awaited<ReturnType<typeof approvalControllerListPending>>,
  TError = unknown,
>(
  params: undefined | ApprovalControllerListPendingParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof approvalControllerListPending>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalControllerListPending>>,
          TError,
          Awaited<ReturnType<typeof approvalControllerListPending>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useApprovalControllerListPending<
  TData = Awaited<ReturnType<typeof approvalControllerListPending>>,
  TError = unknown,
>(
  params?: ApprovalControllerListPendingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof approvalControllerListPending>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalControllerListPending>>,
          TError,
          Awaited<ReturnType<typeof approvalControllerListPending>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useApprovalControllerListPending<
  TData = Awaited<ReturnType<typeof approvalControllerListPending>>,
  TError = unknown,
>(
  params?: ApprovalControllerListPendingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof approvalControllerListPending>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List pending approvals
 */

export function useApprovalControllerListPending<
  TData = Awaited<ReturnType<typeof approvalControllerListPending>>,
  TError = unknown,
>(
  params?: ApprovalControllerListPendingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof approvalControllerListPending>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getApprovalControllerListPendingQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Approve pending action
 */
export type approvalControllerApproveResponse201 = {
  data: void;
  status: 201;
};

export type approvalControllerApproveResponseSuccess = approvalControllerApproveResponse201 & {
  headers: Headers;
};
export type approvalControllerApproveResponse = approvalControllerApproveResponseSuccess;

export const getApprovalControllerApproveUrl = (id: string) => {
  return `/approvals/${id}/approve`;
};

export const approvalControllerApprove = async (
  id: string,
  options?: RequestInit
): Promise<approvalControllerApproveResponse> => {
  return customInstance<approvalControllerApproveResponse>(getApprovalControllerApproveUrl(id), {
    ...options,
    method: 'POST',
  });
};

export const getApprovalControllerApproveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof approvalControllerApprove>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof approvalControllerApprove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['approvalControllerApprove'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof approvalControllerApprove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return approvalControllerApprove(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApprovalControllerApproveMutationResult = NonNullable<
  Awaited<ReturnType<typeof approvalControllerApprove>>
>;

export type ApprovalControllerApproveMutationError = unknown;

/**
 * @summary Approve pending action
 */
export const useApprovalControllerApprove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof approvalControllerApprove>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof approvalControllerApprove>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getApprovalControllerApproveMutationOptions(options), queryClient);
};
/**
 * @summary Reject pending action
 */
export type approvalControllerRejectResponse201 = {
  data: void;
  status: 201;
};

export type approvalControllerRejectResponseSuccess = approvalControllerRejectResponse201 & {
  headers: Headers;
};
export type approvalControllerRejectResponse = approvalControllerRejectResponseSuccess;

export const getApprovalControllerRejectUrl = (id: string) => {
  return `/approvals/${id}/reject`;
};

export const approvalControllerReject = async (
  id: string,
  options?: RequestInit
): Promise<approvalControllerRejectResponse> => {
  return customInstance<approvalControllerRejectResponse>(getApprovalControllerRejectUrl(id), {
    ...options,
    method: 'POST',
  });
};

export const getApprovalControllerRejectMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof approvalControllerReject>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof approvalControllerReject>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['approvalControllerReject'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof approvalControllerReject>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return approvalControllerReject(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApprovalControllerRejectMutationResult = NonNullable<
  Awaited<ReturnType<typeof approvalControllerReject>>
>;

export type ApprovalControllerRejectMutationError = unknown;

/**
 * @summary Reject pending action
 */
export const useApprovalControllerReject = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof approvalControllerReject>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof approvalControllerReject>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getApprovalControllerRejectMutationOptions(options), queryClient);
};
