/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ExecutionListResponseDto,
  ScheduleControllerDelete200,
  ScheduleControllerFindAllParams,
  ScheduleControllerGetExecutionsParams,
  ScheduleListResponseDto,
  ScheduleResponseDto,
} from '../../schemas';

import { customInstance } from '../../axios-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns paginated list of schedules across all user agents
 * @summary List all schedules for user
 */
export type scheduleControllerFindAllResponse200 = {
  data: ScheduleListResponseDto;
  status: 200;
};

export type scheduleControllerFindAllResponseSuccess = scheduleControllerFindAllResponse200 & {
  headers: Headers;
};
export type scheduleControllerFindAllResponse = scheduleControllerFindAllResponseSuccess;

export const getScheduleControllerFindAllUrl = (params?: ScheduleControllerFindAllParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/schedules?${stringifiedParams}` : `/schedules`;
};

export const scheduleControllerFindAll = async (
  params?: ScheduleControllerFindAllParams,
  options?: RequestInit
): Promise<scheduleControllerFindAllResponse> => {
  return customInstance<scheduleControllerFindAllResponse>(
    getScheduleControllerFindAllUrl(params),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getScheduleControllerFindAllQueryKey = (params?: ScheduleControllerFindAllParams) => {
  return [`/schedules`, ...(params ? [params] : [])] as const;
};

export const getScheduleControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof scheduleControllerFindAll>>,
  TError = unknown,
>(
  params?: ScheduleControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerFindAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getScheduleControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof scheduleControllerFindAll>>> = ({
    signal,
  }) => scheduleControllerFindAll(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof scheduleControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ScheduleControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof scheduleControllerFindAll>>
>;
export type ScheduleControllerFindAllQueryError = unknown;

export function useScheduleControllerFindAll<
  TData = Awaited<ReturnType<typeof scheduleControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | ScheduleControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof scheduleControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof scheduleControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useScheduleControllerFindAll<
  TData = Awaited<ReturnType<typeof scheduleControllerFindAll>>,
  TError = unknown,
>(
  params?: ScheduleControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof scheduleControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof scheduleControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useScheduleControllerFindAll<
  TData = Awaited<ReturnType<typeof scheduleControllerFindAll>>,
  TError = unknown,
>(
  params?: ScheduleControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerFindAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List all schedules for user
 */

export function useScheduleControllerFindAll<
  TData = Awaited<ReturnType<typeof scheduleControllerFindAll>>,
  TError = unknown,
>(
  params?: ScheduleControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerFindAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getScheduleControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get schedule by ID
 */
export type scheduleControllerFindOneResponse200 = {
  data: ScheduleResponseDto;
  status: 200;
};

export type scheduleControllerFindOneResponse403 = {
  data: void;
  status: 403;
};

export type scheduleControllerFindOneResponse404 = {
  data: void;
  status: 404;
};

export type scheduleControllerFindOneResponseSuccess = scheduleControllerFindOneResponse200 & {
  headers: Headers;
};
export type scheduleControllerFindOneResponseError = (
  | scheduleControllerFindOneResponse403
  | scheduleControllerFindOneResponse404
) & {
  headers: Headers;
};

export type scheduleControllerFindOneResponse =
  | scheduleControllerFindOneResponseSuccess
  | scheduleControllerFindOneResponseError;

export const getScheduleControllerFindOneUrl = (id: string) => {
  return `/schedules/${id}`;
};

export const scheduleControllerFindOne = async (
  id: string,
  options?: RequestInit
): Promise<scheduleControllerFindOneResponse> => {
  return customInstance<scheduleControllerFindOneResponse>(getScheduleControllerFindOneUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getScheduleControllerFindOneQueryKey = (id?: string) => {
  return [`/schedules/${id}`] as const;
};

export const getScheduleControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof scheduleControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerFindOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getScheduleControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof scheduleControllerFindOne>>> = ({
    signal,
  }) => scheduleControllerFindOne(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof scheduleControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ScheduleControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof scheduleControllerFindOne>>
>;
export type ScheduleControllerFindOneQueryError = void;

export function useScheduleControllerFindOne<
  TData = Awaited<ReturnType<typeof scheduleControllerFindOne>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerFindOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof scheduleControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof scheduleControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useScheduleControllerFindOne<
  TData = Awaited<ReturnType<typeof scheduleControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerFindOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof scheduleControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof scheduleControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useScheduleControllerFindOne<
  TData = Awaited<ReturnType<typeof scheduleControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerFindOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get schedule by ID
 */

export function useScheduleControllerFindOne<
  TData = Awaited<ReturnType<typeof scheduleControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerFindOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getScheduleControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete schedule
 */
export type scheduleControllerDeleteResponse200 = {
  data: ScheduleControllerDelete200;
  status: 200;
};

export type scheduleControllerDeleteResponse403 = {
  data: void;
  status: 403;
};

export type scheduleControllerDeleteResponse404 = {
  data: void;
  status: 404;
};

export type scheduleControllerDeleteResponseSuccess = scheduleControllerDeleteResponse200 & {
  headers: Headers;
};
export type scheduleControllerDeleteResponseError = (
  | scheduleControllerDeleteResponse403
  | scheduleControllerDeleteResponse404
) & {
  headers: Headers;
};

export type scheduleControllerDeleteResponse =
  | scheduleControllerDeleteResponseSuccess
  | scheduleControllerDeleteResponseError;

export const getScheduleControllerDeleteUrl = (id: string) => {
  return `/schedules/${id}`;
};

export const scheduleControllerDelete = async (
  id: string,
  options?: RequestInit
): Promise<scheduleControllerDeleteResponse> => {
  return customInstance<scheduleControllerDeleteResponse>(getScheduleControllerDeleteUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getScheduleControllerDeleteMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof scheduleControllerDelete>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof scheduleControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['scheduleControllerDelete'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof scheduleControllerDelete>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return scheduleControllerDelete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ScheduleControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof scheduleControllerDelete>>
>;

export type ScheduleControllerDeleteMutationError = void;

/**
 * @summary Delete schedule
 */
export const useScheduleControllerDelete = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof scheduleControllerDelete>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof scheduleControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getScheduleControllerDeleteMutationOptions(options), queryClient);
};
/**
 * @summary Pause schedule
 */
export type scheduleControllerPauseResponse200 = {
  data: ScheduleResponseDto;
  status: 200;
};

export type scheduleControllerPauseResponse403 = {
  data: void;
  status: 403;
};

export type scheduleControllerPauseResponse404 = {
  data: void;
  status: 404;
};

export type scheduleControllerPauseResponseSuccess = scheduleControllerPauseResponse200 & {
  headers: Headers;
};
export type scheduleControllerPauseResponseError = (
  | scheduleControllerPauseResponse403
  | scheduleControllerPauseResponse404
) & {
  headers: Headers;
};

export type scheduleControllerPauseResponse =
  | scheduleControllerPauseResponseSuccess
  | scheduleControllerPauseResponseError;

export const getScheduleControllerPauseUrl = (id: string) => {
  return `/schedules/${id}/pause`;
};

export const scheduleControllerPause = async (
  id: string,
  options?: RequestInit
): Promise<scheduleControllerPauseResponse> => {
  return customInstance<scheduleControllerPauseResponse>(getScheduleControllerPauseUrl(id), {
    ...options,
    method: 'PATCH',
  });
};

export const getScheduleControllerPauseMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof scheduleControllerPause>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof scheduleControllerPause>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['scheduleControllerPause'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof scheduleControllerPause>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return scheduleControllerPause(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ScheduleControllerPauseMutationResult = NonNullable<
  Awaited<ReturnType<typeof scheduleControllerPause>>
>;

export type ScheduleControllerPauseMutationError = void;

/**
 * @summary Pause schedule
 */
export const useScheduleControllerPause = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof scheduleControllerPause>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof scheduleControllerPause>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getScheduleControllerPauseMutationOptions(options), queryClient);
};
/**
 * @summary Resume schedule
 */
export type scheduleControllerResumeResponse200 = {
  data: ScheduleResponseDto;
  status: 200;
};

export type scheduleControllerResumeResponse403 = {
  data: void;
  status: 403;
};

export type scheduleControllerResumeResponse404 = {
  data: void;
  status: 404;
};

export type scheduleControllerResumeResponseSuccess = scheduleControllerResumeResponse200 & {
  headers: Headers;
};
export type scheduleControllerResumeResponseError = (
  | scheduleControllerResumeResponse403
  | scheduleControllerResumeResponse404
) & {
  headers: Headers;
};

export type scheduleControllerResumeResponse =
  | scheduleControllerResumeResponseSuccess
  | scheduleControllerResumeResponseError;

export const getScheduleControllerResumeUrl = (id: string) => {
  return `/schedules/${id}/resume`;
};

export const scheduleControllerResume = async (
  id: string,
  options?: RequestInit
): Promise<scheduleControllerResumeResponse> => {
  return customInstance<scheduleControllerResumeResponse>(getScheduleControllerResumeUrl(id), {
    ...options,
    method: 'PATCH',
  });
};

export const getScheduleControllerResumeMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof scheduleControllerResume>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof scheduleControllerResume>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['scheduleControllerResume'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof scheduleControllerResume>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return scheduleControllerResume(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ScheduleControllerResumeMutationResult = NonNullable<
  Awaited<ReturnType<typeof scheduleControllerResume>>
>;

export type ScheduleControllerResumeMutationError = void;

/**
 * @summary Resume schedule
 */
export const useScheduleControllerResume = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof scheduleControllerResume>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof scheduleControllerResume>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getScheduleControllerResumeMutationOptions(options), queryClient);
};
/**
 * Returns paginated list of executions for a specific schedule
 * @summary Get schedule execution history
 */
export type scheduleControllerGetExecutionsResponse200 = {
  data: ExecutionListResponseDto;
  status: 200;
};

export type scheduleControllerGetExecutionsResponse403 = {
  data: void;
  status: 403;
};

export type scheduleControllerGetExecutionsResponse404 = {
  data: void;
  status: 404;
};

export type scheduleControllerGetExecutionsResponseSuccess =
  scheduleControllerGetExecutionsResponse200 & {
    headers: Headers;
  };
export type scheduleControllerGetExecutionsResponseError = (
  | scheduleControllerGetExecutionsResponse403
  | scheduleControllerGetExecutionsResponse404
) & {
  headers: Headers;
};

export type scheduleControllerGetExecutionsResponse =
  | scheduleControllerGetExecutionsResponseSuccess
  | scheduleControllerGetExecutionsResponseError;

export const getScheduleControllerGetExecutionsUrl = (
  id: string,
  params?: ScheduleControllerGetExecutionsParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/schedules/${id}/executions?${stringifiedParams}`
    : `/schedules/${id}/executions`;
};

export const scheduleControllerGetExecutions = async (
  id: string,
  params?: ScheduleControllerGetExecutionsParams,
  options?: RequestInit
): Promise<scheduleControllerGetExecutionsResponse> => {
  return customInstance<scheduleControllerGetExecutionsResponse>(
    getScheduleControllerGetExecutionsUrl(id, params),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getScheduleControllerGetExecutionsQueryKey = (
  id?: string,
  params?: ScheduleControllerGetExecutionsParams
) => {
  return [`/schedules/${id}/executions`, ...(params ? [params] : [])] as const;
};

export const getScheduleControllerGetExecutionsQueryOptions = <
  TData = Awaited<ReturnType<typeof scheduleControllerGetExecutions>>,
  TError = void,
>(
  id: string,
  params?: ScheduleControllerGetExecutionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerGetExecutions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getScheduleControllerGetExecutionsQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof scheduleControllerGetExecutions>>> = ({
    signal,
  }) => scheduleControllerGetExecutions(id, params, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof scheduleControllerGetExecutions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ScheduleControllerGetExecutionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof scheduleControllerGetExecutions>>
>;
export type ScheduleControllerGetExecutionsQueryError = void;

export function useScheduleControllerGetExecutions<
  TData = Awaited<ReturnType<typeof scheduleControllerGetExecutions>>,
  TError = void,
>(
  id: string,
  params: undefined | ScheduleControllerGetExecutionsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerGetExecutions>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof scheduleControllerGetExecutions>>,
          TError,
          Awaited<ReturnType<typeof scheduleControllerGetExecutions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useScheduleControllerGetExecutions<
  TData = Awaited<ReturnType<typeof scheduleControllerGetExecutions>>,
  TError = void,
>(
  id: string,
  params?: ScheduleControllerGetExecutionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerGetExecutions>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof scheduleControllerGetExecutions>>,
          TError,
          Awaited<ReturnType<typeof scheduleControllerGetExecutions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useScheduleControllerGetExecutions<
  TData = Awaited<ReturnType<typeof scheduleControllerGetExecutions>>,
  TError = void,
>(
  id: string,
  params?: ScheduleControllerGetExecutionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerGetExecutions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get schedule execution history
 */

export function useScheduleControllerGetExecutions<
  TData = Awaited<ReturnType<typeof scheduleControllerGetExecutions>>,
  TError = void,
>(
  id: string,
  params?: ScheduleControllerGetExecutionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof scheduleControllerGetExecutions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getScheduleControllerGetExecutionsQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
