/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */

export type AgentControllerListSessionsStatus =
  (typeof AgentControllerListSessionsStatus)[keyof typeof AgentControllerListSessionsStatus];

export const AgentControllerListSessionsStatus = {
  ACTIVE: 'ACTIVE',
  WAITING_APPROVAL: 'WAITING_APPROVAL',
  COMPLETED: 'COMPLETED',
  ERROR: 'ERROR',
} as const;
