/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */
import type { AgentControllerFindAllStatus } from './agentControllerFindAllStatus';

export type AgentControllerFindAllParams = {
  page?: number;
  pageSize?: number;
  status?: AgentControllerFindAllStatus;
};
