/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */
import type { CreateAgentDtoConfig } from './createAgentDtoConfig';
import type { CreateAgentDtoPermissions } from './createAgentDtoPermissions';

export interface CreateAgentDto {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  config?: CreateAgentDtoConfig;
  permissions?: CreateAgentDtoPermissions;
}
