/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */
import type { CreateAgentDtoPermissionsMemory } from './createAgentDtoPermissionsMemory';
import type { CreateAgentDtoPermissionsRead } from './createAgentDtoPermissionsRead';
import type { CreateAgentDtoPermissionsSchedule } from './createAgentDtoPermissionsSchedule';
import type { CreateAgentDtoPermissionsWrite } from './createAgentDtoPermissionsWrite';

export type CreateAgentDtoPermissions = {
  read: CreateAgentDtoPermissionsRead;
  write: CreateAgentDtoPermissionsWrite;
  memory: CreateAgentDtoPermissionsMemory;
  schedule: CreateAgentDtoPermissionsSchedule;
};
