/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */
import type { CreateAgentDtoPermissionsWriteTargetsActionsRulesItem } from './createAgentDtoPermissionsWriteTargetsActionsRulesItem';
import type { CreateAgentDtoPermissionsWriteTargetsActionsTier } from './createAgentDtoPermissionsWriteTargetsActionsTier';

export type CreateAgentDtoPermissionsWriteTargetsActions = {
  [key: string]: {
    allowed: boolean;
    tier: CreateAgentDtoPermissionsWriteTargetsActionsTier;
    rules?: CreateAgentDtoPermissionsWriteTargetsActionsRulesItem[];
  };
};
