/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */

export interface CreateWalletDto {
  /** @pattern ^0x[a-fA-F0-9]{40}$ */
  address: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** @pattern ^0x[a-fA-F0-9]{64}$ */
  privateKey: string;
}
