/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */

export type CreateAgentDtoPermissionsWriteTargetsActionsRulesItemConditionOperator =
  (typeof CreateAgentDtoPermissionsWriteTargetsActionsRulesItemConditionOperator)[keyof typeof CreateAgentDtoPermissionsWriteTargetsActionsRulesItemConditionOperator];

export const CreateAgentDtoPermissionsWriteTargetsActionsRulesItemConditionOperator = {
  eq: 'eq',
  neq: 'neq',
  gt: 'gt',
  lt: 'lt',
  gte: 'gte',
  lte: 'lte',
  in: 'in',
  notIn: 'notIn',
} as const;
