/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */

export type ScheduleControllerGetExecutionsParams = {
  /**
   * Maximum number of executions to return (default: 20)
   */
  limit?: number;
  /**
   * Number of executions to skip (default: 0)
   */
  offset?: number;
};
