/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */

/**
 * Next scheduled run timestamp
 */
export type ScheduleResponseDtoNextRunAt = { [key: string]: unknown };
