/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */

export interface ScheduleConfigDto {
  /** Cron expression */
  cron: string;
  /** Timezone */
  timezone: string;
  /** Prompt to execute */
  prompt: string;
  /** Whether schedule is enabled */
  enabled: boolean;
  /** Max number of runs */
  maxRuns?: number;
}
