/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */
import type { ScheduleConfigDto } from './scheduleConfigDto';
import type { ScheduleResponseDtoLastError } from './scheduleResponseDtoLastError';
import type { ScheduleResponseDtoLastRunAt } from './scheduleResponseDtoLastRunAt';
import type { ScheduleResponseDtoNextRunAt } from './scheduleResponseDtoNextRunAt';
import type { ScheduleResponseDtoStatus } from './scheduleResponseDtoStatus';

export interface ScheduleResponseDto {
  id: string;
  agentId: string;
  /** Agent name */
  agentName: string;
  config: ScheduleConfigDto;
  status: ScheduleResponseDtoStatus;
  /** Number of times run */
  runCount: number;
  /** Last run timestamp */
  lastRunAt?: ScheduleResponseDtoLastRunAt;
  /** Next scheduled run timestamp */
  nextRunAt?: ScheduleResponseDtoNextRunAt;
  /** Last error message */
  lastError?: ScheduleResponseDtoLastError;
  createdAt: string;
  updatedAt: string;
}
