/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */

export type ScheduleResponseDtoStatus =
  (typeof ScheduleResponseDtoStatus)[keyof typeof ScheduleResponseDtoStatus];

export const ScheduleResponseDtoStatus = {
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
  ERROR: 'ERROR',
} as const;
