/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */

export interface SendMessageDto {
  /**
   * @minLength 1
   * @maxLength 10000
   */
  content: string;
}
