/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */
import type { UpdateAgentDtoConfig } from './updateAgentDtoConfig';
import type { UpdateAgentDtoPermissions } from './updateAgentDtoPermissions';
import type { UpdateAgentDtoStatus } from './updateAgentDtoStatus';

export interface UpdateAgentDto {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name?: string;
  config?: UpdateAgentDtoConfig;
  permissions?: UpdateAgentDtoPermissions;
  status?: UpdateAgentDtoStatus;
}
