/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */

export type UpdateAgentDtoStatus = (typeof UpdateAgentDtoStatus)[keyof typeof UpdateAgentDtoStatus];

export const UpdateAgentDtoStatus = {
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  ARCHIVED: 'ARCHIVED',
} as const;
