/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */
import type { UpdateAgentDtoPermissionsWriteTargetsActionsRulesItemConditionOperator } from './updateAgentDtoPermissionsWriteTargetsActionsRulesItemConditionOperator';

export type UpdateAgentDtoPermissionsWriteTargetsActionsRulesItemCondition = {
  field: string;
  operator: UpdateAgentDtoPermissionsWriteTargetsActionsRulesItemConditionOperator;
  value: unknown;
};
