/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */

export type UpdateAgentDtoPermissionsWriteDefaultTier =
  (typeof UpdateAgentDtoPermissionsWriteDefaultTier)[keyof typeof UpdateAgentDtoPermissionsWriteDefaultTier];

export const UpdateAgentDtoPermissionsWriteDefaultTier = {
  auto: 'auto',
  notify: 'notify',
  approve: 'approve',
  block: 'block',
} as const;
