/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */
import type { UpdateAgentDtoPermissionsMemory } from './updateAgentDtoPermissionsMemory';
import type { UpdateAgentDtoPermissionsRead } from './updateAgentDtoPermissionsRead';
import type { UpdateAgentDtoPermissionsSchedule } from './updateAgentDtoPermissionsSchedule';
import type { UpdateAgentDtoPermissionsWrite } from './updateAgentDtoPermissionsWrite';

export type UpdateAgentDtoPermissions = {
  read: UpdateAgentDtoPermissionsRead;
  write: UpdateAgentDtoPermissionsWrite;
  memory: UpdateAgentDtoPermissionsMemory;
  schedule: UpdateAgentDtoPermissionsSchedule;
};
