/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */
import type { UpdateAgentDtoPermissionsWriteTargetsActionsRulesItemCondition } from './updateAgentDtoPermissionsWriteTargetsActionsRulesItemCondition';
import type { UpdateAgentDtoPermissionsWriteTargetsActionsRulesItemTier } from './updateAgentDtoPermissionsWriteTargetsActionsRulesItemTier';

export type UpdateAgentDtoPermissionsWriteTargetsActionsRulesItem = {
  condition: UpdateAgentDtoPermissionsWriteTargetsActionsRulesItemCondition;
  tier: UpdateAgentDtoPermissionsWriteTargetsActionsRulesItemTier;
};
