/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */
import type { WalletResponseDtoType } from './walletResponseDtoType';

export interface WalletResponseDto {
  id: string;
  address: string;
  name: string;
  type: WalletResponseDtoType;
  ownerId: string;
  /** @nullable */
  agentId: string | null;
  createdAt: unknown;
  updatedAt: unknown;
}
