/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */

export type WalletControllerFindAllParams = {
  /**
   * Page number (default: 1)
   */
  page?: number;
  /**
   * Items per page (default: 20)
   */
  pageSize?: number;
};
