/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */

export type WalletAssetsResponseDtoTokensItem = {
  address: string;
  symbol: string;
  name: string;
  decimals: number;
  balance: string;
  balanceFormatted: string;
  /** @nullable */
  usdValue: number | null;
};
