/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */
import type { WalletAssetsResponseDtoTokensItem } from './walletAssetsResponseDtoTokensItem';

export interface WalletAssetsResponseDto {
  walletId: string;
  address: string;
  network: string;
  tokens: WalletAssetsResponseDtoTokensItem[];
  /** @nullable */
  totalUsdValue: number | null;
  fetchedAt: unknown;
}
