/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AgentControllerAssignWallet200,
  AgentControllerFindAllParams,
  AgentControllerListNotesParams,
  AgentControllerListSessionsParams,
  AssignWalletDto,
  CreateAgentDto,
  UpdateAgentDto,
} from '../../schemas';

import { customInstance } from '../../axios-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create a new agent
 */
export type agentControllerCreateResponse201 = {
  data: void;
  status: 201;
};

export type agentControllerCreateResponseSuccess = agentControllerCreateResponse201 & {
  headers: Headers;
};
export type agentControllerCreateResponse = agentControllerCreateResponseSuccess;

export const getAgentControllerCreateUrl = () => {
  return `/agents`;
};

export const agentControllerCreate = async (
  createAgentDto: CreateAgentDto,
  options?: RequestInit
): Promise<agentControllerCreateResponse> => {
  return customInstance<agentControllerCreateResponse>(getAgentControllerCreateUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createAgentDto),
  });
};

export const getAgentControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof agentControllerCreate>>,
    TError,
    { data: CreateAgentDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof agentControllerCreate>>,
  TError,
  { data: CreateAgentDto },
  TContext
> => {
  const mutationKey = ['agentControllerCreate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof agentControllerCreate>>,
    { data: CreateAgentDto }
  > = (props) => {
    const { data } = props ?? {};

    return agentControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AgentControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof agentControllerCreate>>
>;
export type AgentControllerCreateMutationBody = CreateAgentDto;
export type AgentControllerCreateMutationError = unknown;

/**
 * @summary Create a new agent
 */
export const useAgentControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof agentControllerCreate>>,
      TError,
      { data: CreateAgentDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof agentControllerCreate>>,
  TError,
  { data: CreateAgentDto },
  TContext
> => {
  return useMutation(getAgentControllerCreateMutationOptions(options), queryClient);
};
/**
 * @summary List user agents
 */
export type agentControllerFindAllResponse200 = {
  data: void;
  status: 200;
};

export type agentControllerFindAllResponseSuccess = agentControllerFindAllResponse200 & {
  headers: Headers;
};
export type agentControllerFindAllResponse = agentControllerFindAllResponseSuccess;

export const getAgentControllerFindAllUrl = (params?: AgentControllerFindAllParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/agents?${stringifiedParams}` : `/agents`;
};

export const agentControllerFindAll = async (
  params?: AgentControllerFindAllParams,
  options?: RequestInit
): Promise<agentControllerFindAllResponse> => {
  return customInstance<agentControllerFindAllResponse>(getAgentControllerFindAllUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getAgentControllerFindAllQueryKey = (params?: AgentControllerFindAllParams) => {
  return [`/agents`, ...(params ? [params] : [])] as const;
};

export const getAgentControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof agentControllerFindAll>>,
  TError = unknown,
>(
  params?: AgentControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerFindAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAgentControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof agentControllerFindAll>>> = ({ signal }) =>
    agentControllerFindAll(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof agentControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AgentControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof agentControllerFindAll>>
>;
export type AgentControllerFindAllQueryError = unknown;

export function useAgentControllerFindAll<
  TData = Awaited<ReturnType<typeof agentControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | AgentControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agentControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof agentControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAgentControllerFindAll<
  TData = Awaited<ReturnType<typeof agentControllerFindAll>>,
  TError = unknown,
>(
  params?: AgentControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agentControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof agentControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAgentControllerFindAll<
  TData = Awaited<ReturnType<typeof agentControllerFindAll>>,
  TError = unknown,
>(
  params?: AgentControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerFindAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List user agents
 */

export function useAgentControllerFindAll<
  TData = Awaited<ReturnType<typeof agentControllerFindAll>>,
  TError = unknown,
>(
  params?: AgentControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerFindAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAgentControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get agent by ID
 */
export type agentControllerFindOneResponse200 = {
  data: void;
  status: 200;
};

export type agentControllerFindOneResponseSuccess = agentControllerFindOneResponse200 & {
  headers: Headers;
};
export type agentControllerFindOneResponse = agentControllerFindOneResponseSuccess;

export const getAgentControllerFindOneUrl = (id: string) => {
  return `/agents/${id}`;
};

export const agentControllerFindOne = async (
  id: string,
  options?: RequestInit
): Promise<agentControllerFindOneResponse> => {
  return customInstance<agentControllerFindOneResponse>(getAgentControllerFindOneUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getAgentControllerFindOneQueryKey = (id?: string) => {
  return [`/agents/${id}`] as const;
};

export const getAgentControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof agentControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerFindOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAgentControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof agentControllerFindOne>>> = ({ signal }) =>
    agentControllerFindOne(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof agentControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AgentControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof agentControllerFindOne>>
>;
export type AgentControllerFindOneQueryError = unknown;

export function useAgentControllerFindOne<
  TData = Awaited<ReturnType<typeof agentControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerFindOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agentControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof agentControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAgentControllerFindOne<
  TData = Awaited<ReturnType<typeof agentControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerFindOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agentControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof agentControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAgentControllerFindOne<
  TData = Awaited<ReturnType<typeof agentControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerFindOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get agent by ID
 */

export function useAgentControllerFindOne<
  TData = Awaited<ReturnType<typeof agentControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerFindOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAgentControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update agent
 */
export type agentControllerUpdateResponse200 = {
  data: void;
  status: 200;
};

export type agentControllerUpdateResponseSuccess = agentControllerUpdateResponse200 & {
  headers: Headers;
};
export type agentControllerUpdateResponse = agentControllerUpdateResponseSuccess;

export const getAgentControllerUpdateUrl = (id: string) => {
  return `/agents/${id}`;
};

export const agentControllerUpdate = async (
  id: string,
  updateAgentDto: UpdateAgentDto,
  options?: RequestInit
): Promise<agentControllerUpdateResponse> => {
  return customInstance<agentControllerUpdateResponse>(getAgentControllerUpdateUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateAgentDto),
  });
};

export const getAgentControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof agentControllerUpdate>>,
    TError,
    { id: string; data: UpdateAgentDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof agentControllerUpdate>>,
  TError,
  { id: string; data: UpdateAgentDto },
  TContext
> => {
  const mutationKey = ['agentControllerUpdate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof agentControllerUpdate>>,
    { id: string; data: UpdateAgentDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return agentControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AgentControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof agentControllerUpdate>>
>;
export type AgentControllerUpdateMutationBody = UpdateAgentDto;
export type AgentControllerUpdateMutationError = unknown;

/**
 * @summary Update agent
 */
export const useAgentControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof agentControllerUpdate>>,
      TError,
      { id: string; data: UpdateAgentDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof agentControllerUpdate>>,
  TError,
  { id: string; data: UpdateAgentDto },
  TContext
> => {
  return useMutation(getAgentControllerUpdateMutationOptions(options), queryClient);
};
/**
 * @summary Archive agent (soft delete)
 */
export type agentControllerArchiveResponse200 = {
  data: void;
  status: 200;
};

export type agentControllerArchiveResponseSuccess = agentControllerArchiveResponse200 & {
  headers: Headers;
};
export type agentControllerArchiveResponse = agentControllerArchiveResponseSuccess;

export const getAgentControllerArchiveUrl = (id: string) => {
  return `/agents/${id}`;
};

export const agentControllerArchive = async (
  id: string,
  options?: RequestInit
): Promise<agentControllerArchiveResponse> => {
  return customInstance<agentControllerArchiveResponse>(getAgentControllerArchiveUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getAgentControllerArchiveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof agentControllerArchive>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof agentControllerArchive>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['agentControllerArchive'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof agentControllerArchive>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return agentControllerArchive(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AgentControllerArchiveMutationResult = NonNullable<
  Awaited<ReturnType<typeof agentControllerArchive>>
>;

export type AgentControllerArchiveMutationError = unknown;

/**
 * @summary Archive agent (soft delete)
 */
export const useAgentControllerArchive = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof agentControllerArchive>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof agentControllerArchive>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getAgentControllerArchiveMutationOptions(options), queryClient);
};
/**
 * Binds a wallet to the agent. The wallet must belong to the same owner. When the wallet changes, a system message is added to all active sessions.
 * @summary Assign or unassign wallet to agent
 */
export type agentControllerAssignWalletResponse200 = {
  data: AgentControllerAssignWallet200;
  status: 200;
};

export type agentControllerAssignWalletResponse400 = {
  data: void;
  status: 400;
};

export type agentControllerAssignWalletResponse403 = {
  data: void;
  status: 403;
};

export type agentControllerAssignWalletResponse404 = {
  data: void;
  status: 404;
};

export type agentControllerAssignWalletResponseSuccess = agentControllerAssignWalletResponse200 & {
  headers: Headers;
};
export type agentControllerAssignWalletResponseError = (
  | agentControllerAssignWalletResponse400
  | agentControllerAssignWalletResponse403
  | agentControllerAssignWalletResponse404
) & {
  headers: Headers;
};

export type agentControllerAssignWalletResponse =
  | agentControllerAssignWalletResponseSuccess
  | agentControllerAssignWalletResponseError;

export const getAgentControllerAssignWalletUrl = (id: string) => {
  return `/agents/${id}/wallet`;
};

export const agentControllerAssignWallet = async (
  id: string,
  assignWalletDto: AssignWalletDto,
  options?: RequestInit
): Promise<agentControllerAssignWalletResponse> => {
  return customInstance<agentControllerAssignWalletResponse>(
    getAgentControllerAssignWalletUrl(id),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(assignWalletDto),
    }
  );
};

export const getAgentControllerAssignWalletMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof agentControllerAssignWallet>>,
    TError,
    { id: string; data: AssignWalletDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof agentControllerAssignWallet>>,
  TError,
  { id: string; data: AssignWalletDto },
  TContext
> => {
  const mutationKey = ['agentControllerAssignWallet'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof agentControllerAssignWallet>>,
    { id: string; data: AssignWalletDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return agentControllerAssignWallet(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AgentControllerAssignWalletMutationResult = NonNullable<
  Awaited<ReturnType<typeof agentControllerAssignWallet>>
>;
export type AgentControllerAssignWalletMutationBody = AssignWalletDto;
export type AgentControllerAssignWalletMutationError = void;

/**
 * @summary Assign or unassign wallet to agent
 */
export const useAgentControllerAssignWallet = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof agentControllerAssignWallet>>,
      TError,
      { id: string; data: AssignWalletDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof agentControllerAssignWallet>>,
  TError,
  { id: string; data: AssignWalletDto },
  TContext
> => {
  return useMutation(getAgentControllerAssignWalletMutationOptions(options), queryClient);
};
/**
 * @summary List agent sessions
 */
export type agentControllerListSessionsResponse200 = {
  data: void;
  status: 200;
};

export type agentControllerListSessionsResponseSuccess = agentControllerListSessionsResponse200 & {
  headers: Headers;
};
export type agentControllerListSessionsResponse = agentControllerListSessionsResponseSuccess;

export const getAgentControllerListSessionsUrl = (
  id: string,
  params?: AgentControllerListSessionsParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/agents/${id}/sessions?${stringifiedParams}`
    : `/agents/${id}/sessions`;
};

export const agentControllerListSessions = async (
  id: string,
  params?: AgentControllerListSessionsParams,
  options?: RequestInit
): Promise<agentControllerListSessionsResponse> => {
  return customInstance<agentControllerListSessionsResponse>(
    getAgentControllerListSessionsUrl(id, params),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getAgentControllerListSessionsQueryKey = (
  id?: string,
  params?: AgentControllerListSessionsParams
) => {
  return [`/agents/${id}/sessions`, ...(params ? [params] : [])] as const;
};

export const getAgentControllerListSessionsQueryOptions = <
  TData = Awaited<ReturnType<typeof agentControllerListSessions>>,
  TError = unknown,
>(
  id: string,
  params?: AgentControllerListSessionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerListSessions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAgentControllerListSessionsQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof agentControllerListSessions>>> = ({
    signal,
  }) => agentControllerListSessions(id, params, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof agentControllerListSessions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AgentControllerListSessionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof agentControllerListSessions>>
>;
export type AgentControllerListSessionsQueryError = unknown;

export function useAgentControllerListSessions<
  TData = Awaited<ReturnType<typeof agentControllerListSessions>>,
  TError = unknown,
>(
  id: string,
  params: undefined | AgentControllerListSessionsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerListSessions>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agentControllerListSessions>>,
          TError,
          Awaited<ReturnType<typeof agentControllerListSessions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAgentControllerListSessions<
  TData = Awaited<ReturnType<typeof agentControllerListSessions>>,
  TError = unknown,
>(
  id: string,
  params?: AgentControllerListSessionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerListSessions>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agentControllerListSessions>>,
          TError,
          Awaited<ReturnType<typeof agentControllerListSessions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAgentControllerListSessions<
  TData = Awaited<ReturnType<typeof agentControllerListSessions>>,
  TError = unknown,
>(
  id: string,
  params?: AgentControllerListSessionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerListSessions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List agent sessions
 */

export function useAgentControllerListSessions<
  TData = Awaited<ReturnType<typeof agentControllerListSessions>>,
  TError = unknown,
>(
  id: string,
  params?: AgentControllerListSessionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerListSessions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAgentControllerListSessionsQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List agent notes
 */
export type agentControllerListNotesResponse200 = {
  data: void;
  status: 200;
};

export type agentControllerListNotesResponseSuccess = agentControllerListNotesResponse200 & {
  headers: Headers;
};
export type agentControllerListNotesResponse = agentControllerListNotesResponseSuccess;

export const getAgentControllerListNotesUrl = (
  id: string,
  params?: AgentControllerListNotesParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/agents/${id}/notes?${stringifiedParams}`
    : `/agents/${id}/notes`;
};

export const agentControllerListNotes = async (
  id: string,
  params?: AgentControllerListNotesParams,
  options?: RequestInit
): Promise<agentControllerListNotesResponse> => {
  return customInstance<agentControllerListNotesResponse>(
    getAgentControllerListNotesUrl(id, params),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getAgentControllerListNotesQueryKey = (
  id?: string,
  params?: AgentControllerListNotesParams
) => {
  return [`/agents/${id}/notes`, ...(params ? [params] : [])] as const;
};

export const getAgentControllerListNotesQueryOptions = <
  TData = Awaited<ReturnType<typeof agentControllerListNotes>>,
  TError = unknown,
>(
  id: string,
  params?: AgentControllerListNotesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerListNotes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAgentControllerListNotesQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof agentControllerListNotes>>> = ({
    signal,
  }) => agentControllerListNotes(id, params, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof agentControllerListNotes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AgentControllerListNotesQueryResult = NonNullable<
  Awaited<ReturnType<typeof agentControllerListNotes>>
>;
export type AgentControllerListNotesQueryError = unknown;

export function useAgentControllerListNotes<
  TData = Awaited<ReturnType<typeof agentControllerListNotes>>,
  TError = unknown,
>(
  id: string,
  params: undefined | AgentControllerListNotesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerListNotes>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agentControllerListNotes>>,
          TError,
          Awaited<ReturnType<typeof agentControllerListNotes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAgentControllerListNotes<
  TData = Awaited<ReturnType<typeof agentControllerListNotes>>,
  TError = unknown,
>(
  id: string,
  params?: AgentControllerListNotesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerListNotes>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agentControllerListNotes>>,
          TError,
          Awaited<ReturnType<typeof agentControllerListNotes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAgentControllerListNotes<
  TData = Awaited<ReturnType<typeof agentControllerListNotes>>,
  TError = unknown,
>(
  id: string,
  params?: AgentControllerListNotesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerListNotes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List agent notes
 */

export function useAgentControllerListNotes<
  TData = Awaited<ReturnType<typeof agentControllerListNotes>>,
  TError = unknown,
>(
  id: string,
  params?: AgentControllerListNotesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerListNotes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAgentControllerListNotesQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List agent schedules
 */
export type agentControllerListSchedulesResponse200 = {
  data: void;
  status: 200;
};

export type agentControllerListSchedulesResponseSuccess =
  agentControllerListSchedulesResponse200 & {
    headers: Headers;
  };
export type agentControllerListSchedulesResponse = agentControllerListSchedulesResponseSuccess;

export const getAgentControllerListSchedulesUrl = (id: string) => {
  return `/agents/${id}/schedules`;
};

export const agentControllerListSchedules = async (
  id: string,
  options?: RequestInit
): Promise<agentControllerListSchedulesResponse> => {
  return customInstance<agentControllerListSchedulesResponse>(
    getAgentControllerListSchedulesUrl(id),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getAgentControllerListSchedulesQueryKey = (id?: string) => {
  return [`/agents/${id}/schedules`] as const;
};

export const getAgentControllerListSchedulesQueryOptions = <
  TData = Awaited<ReturnType<typeof agentControllerListSchedules>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerListSchedules>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAgentControllerListSchedulesQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof agentControllerListSchedules>>> = ({
    signal,
  }) => agentControllerListSchedules(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof agentControllerListSchedules>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AgentControllerListSchedulesQueryResult = NonNullable<
  Awaited<ReturnType<typeof agentControllerListSchedules>>
>;
export type AgentControllerListSchedulesQueryError = unknown;

export function useAgentControllerListSchedules<
  TData = Awaited<ReturnType<typeof agentControllerListSchedules>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerListSchedules>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agentControllerListSchedules>>,
          TError,
          Awaited<ReturnType<typeof agentControllerListSchedules>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAgentControllerListSchedules<
  TData = Awaited<ReturnType<typeof agentControllerListSchedules>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerListSchedules>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agentControllerListSchedules>>,
          TError,
          Awaited<ReturnType<typeof agentControllerListSchedules>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAgentControllerListSchedules<
  TData = Awaited<ReturnType<typeof agentControllerListSchedules>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerListSchedules>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List agent schedules
 */

export function useAgentControllerListSchedules<
  TData = Awaited<ReturnType<typeof agentControllerListSchedules>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof agentControllerListSchedules>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAgentControllerListSchedulesQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create schedule
 */
export type agentControllerCreateScheduleResponse201 = {
  data: void;
  status: 201;
};

export type agentControllerCreateScheduleResponseSuccess =
  agentControllerCreateScheduleResponse201 & {
    headers: Headers;
  };
export type agentControllerCreateScheduleResponse = agentControllerCreateScheduleResponseSuccess;

export const getAgentControllerCreateScheduleUrl = (id: string) => {
  return `/agents/${id}/schedules`;
};

export const agentControllerCreateSchedule = async (
  id: string,
  options?: RequestInit
): Promise<agentControllerCreateScheduleResponse> => {
  return customInstance<agentControllerCreateScheduleResponse>(
    getAgentControllerCreateScheduleUrl(id),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getAgentControllerCreateScheduleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof agentControllerCreateSchedule>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof agentControllerCreateSchedule>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['agentControllerCreateSchedule'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof agentControllerCreateSchedule>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return agentControllerCreateSchedule(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AgentControllerCreateScheduleMutationResult = NonNullable<
  Awaited<ReturnType<typeof agentControllerCreateSchedule>>
>;

export type AgentControllerCreateScheduleMutationError = unknown;

/**
 * @summary Create schedule
 */
export const useAgentControllerCreateSchedule = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof agentControllerCreateSchedule>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof agentControllerCreateSchedule>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getAgentControllerCreateScheduleMutationOptions(options), queryClient);
};
/**
 * @summary Update schedule
 */
export type agentControllerUpdateScheduleResponse200 = {
  data: void;
  status: 200;
};

export type agentControllerUpdateScheduleResponseSuccess =
  agentControllerUpdateScheduleResponse200 & {
    headers: Headers;
  };
export type agentControllerUpdateScheduleResponse = agentControllerUpdateScheduleResponseSuccess;

export const getAgentControllerUpdateScheduleUrl = (id: string, scheduleId: string) => {
  return `/agents/${id}/schedules/${scheduleId}`;
};

export const agentControllerUpdateSchedule = async (
  id: string,
  scheduleId: string,
  options?: RequestInit
): Promise<agentControllerUpdateScheduleResponse> => {
  return customInstance<agentControllerUpdateScheduleResponse>(
    getAgentControllerUpdateScheduleUrl(id, scheduleId),
    {
      ...options,
      method: 'PATCH',
    }
  );
};

export const getAgentControllerUpdateScheduleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof agentControllerUpdateSchedule>>,
    TError,
    { id: string; scheduleId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof agentControllerUpdateSchedule>>,
  TError,
  { id: string; scheduleId: string },
  TContext
> => {
  const mutationKey = ['agentControllerUpdateSchedule'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof agentControllerUpdateSchedule>>,
    { id: string; scheduleId: string }
  > = (props) => {
    const { id, scheduleId } = props ?? {};

    return agentControllerUpdateSchedule(id, scheduleId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AgentControllerUpdateScheduleMutationResult = NonNullable<
  Awaited<ReturnType<typeof agentControllerUpdateSchedule>>
>;

export type AgentControllerUpdateScheduleMutationError = unknown;

/**
 * @summary Update schedule
 */
export const useAgentControllerUpdateSchedule = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof agentControllerUpdateSchedule>>,
      TError,
      { id: string; scheduleId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof agentControllerUpdateSchedule>>,
  TError,
  { id: string; scheduleId: string },
  TContext
> => {
  return useMutation(getAgentControllerUpdateScheduleMutationOptions(options), queryClient);
};
/**
 * @summary Delete schedule
 */
export type agentControllerDeleteScheduleResponse200 = {
  data: void;
  status: 200;
};

export type agentControllerDeleteScheduleResponseSuccess =
  agentControllerDeleteScheduleResponse200 & {
    headers: Headers;
  };
export type agentControllerDeleteScheduleResponse = agentControllerDeleteScheduleResponseSuccess;

export const getAgentControllerDeleteScheduleUrl = (id: string, scheduleId: string) => {
  return `/agents/${id}/schedules/${scheduleId}`;
};

export const agentControllerDeleteSchedule = async (
  id: string,
  scheduleId: string,
  options?: RequestInit
): Promise<agentControllerDeleteScheduleResponse> => {
  return customInstance<agentControllerDeleteScheduleResponse>(
    getAgentControllerDeleteScheduleUrl(id, scheduleId),
    {
      ...options,
      method: 'DELETE',
    }
  );
};

export const getAgentControllerDeleteScheduleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof agentControllerDeleteSchedule>>,
    TError,
    { id: string; scheduleId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof agentControllerDeleteSchedule>>,
  TError,
  { id: string; scheduleId: string },
  TContext
> => {
  const mutationKey = ['agentControllerDeleteSchedule'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof agentControllerDeleteSchedule>>,
    { id: string; scheduleId: string }
  > = (props) => {
    const { id, scheduleId } = props ?? {};

    return agentControllerDeleteSchedule(id, scheduleId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AgentControllerDeleteScheduleMutationResult = NonNullable<
  Awaited<ReturnType<typeof agentControllerDeleteSchedule>>
>;

export type AgentControllerDeleteScheduleMutationError = unknown;

/**
 * @summary Delete schedule
 */
export const useAgentControllerDeleteSchedule = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof agentControllerDeleteSchedule>>,
      TError,
      { id: string; scheduleId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof agentControllerDeleteSchedule>>,
  TError,
  { id: string; scheduleId: string },
  TContext
> => {
  return useMutation(getAgentControllerDeleteScheduleMutationOptions(options), queryClient);
};
