/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateSessionDto, ResolveApprovalDto, SendMessageDto } from '../../schemas';

import { customInstance } from '../../axios-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create a new session
 */
export type sessionControllerCreateSessionResponse201 = {
  data: void;
  status: 201;
};

export type sessionControllerCreateSessionResponseSuccess =
  sessionControllerCreateSessionResponse201 & {
    headers: Headers;
  };
export type sessionControllerCreateSessionResponse = sessionControllerCreateSessionResponseSuccess;

export const getSessionControllerCreateSessionUrl = () => {
  return `/sessions`;
};

export const sessionControllerCreateSession = async (
  createSessionDto: CreateSessionDto,
  options?: RequestInit
): Promise<sessionControllerCreateSessionResponse> => {
  return customInstance<sessionControllerCreateSessionResponse>(
    getSessionControllerCreateSessionUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createSessionDto),
    }
  );
};

export const getSessionControllerCreateSessionMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sessionControllerCreateSession>>,
    TError,
    { data: CreateSessionDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sessionControllerCreateSession>>,
  TError,
  { data: CreateSessionDto },
  TContext
> => {
  const mutationKey = ['sessionControllerCreateSession'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sessionControllerCreateSession>>,
    { data: CreateSessionDto }
  > = (props) => {
    const { data } = props ?? {};

    return sessionControllerCreateSession(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SessionControllerCreateSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerCreateSession>>
>;
export type SessionControllerCreateSessionMutationBody = CreateSessionDto;
export type SessionControllerCreateSessionMutationError = unknown;

/**
 * @summary Create a new session
 */
export const useSessionControllerCreateSession = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sessionControllerCreateSession>>,
      TError,
      { data: CreateSessionDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof sessionControllerCreateSession>>,
  TError,
  { data: CreateSessionDto },
  TContext
> => {
  return useMutation(getSessionControllerCreateSessionMutationOptions(options), queryClient);
};
/**
 * @summary Get session state and messages
 */
export type sessionControllerGetSessionResponse200 = {
  data: void;
  status: 200;
};

export type sessionControllerGetSessionResponse404 = {
  data: void;
  status: 404;
};

export type sessionControllerGetSessionResponseSuccess = sessionControllerGetSessionResponse200 & {
  headers: Headers;
};
export type sessionControllerGetSessionResponseError = sessionControllerGetSessionResponse404 & {
  headers: Headers;
};

export type sessionControllerGetSessionResponse =
  | sessionControllerGetSessionResponseSuccess
  | sessionControllerGetSessionResponseError;

export const getSessionControllerGetSessionUrl = (id: string) => {
  return `/sessions/${id}`;
};

export const sessionControllerGetSession = async (
  id: string,
  options?: RequestInit
): Promise<sessionControllerGetSessionResponse> => {
  return customInstance<sessionControllerGetSessionResponse>(
    getSessionControllerGetSessionUrl(id),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getSessionControllerGetSessionQueryKey = (id?: string) => {
  return [`/sessions/${id}`] as const;
};

export const getSessionControllerGetSessionQueryOptions = <
  TData = Awaited<ReturnType<typeof sessionControllerGetSession>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionControllerGetSession>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSessionControllerGetSessionQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof sessionControllerGetSession>>> = ({
    signal,
  }) => sessionControllerGetSession(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof sessionControllerGetSession>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SessionControllerGetSessionQueryResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerGetSession>>
>;
export type SessionControllerGetSessionQueryError = void;

export function useSessionControllerGetSession<
  TData = Awaited<ReturnType<typeof sessionControllerGetSession>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionControllerGetSession>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerGetSession>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerGetSession>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSessionControllerGetSession<
  TData = Awaited<ReturnType<typeof sessionControllerGetSession>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionControllerGetSession>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerGetSession>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerGetSession>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSessionControllerGetSession<
  TData = Awaited<ReturnType<typeof sessionControllerGetSession>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionControllerGetSession>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get session state and messages
 */

export function useSessionControllerGetSession<
  TData = Awaited<ReturnType<typeof sessionControllerGetSession>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionControllerGetSession>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSessionControllerGetSessionQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete a session
 */
export type sessionControllerDeleteSessionResponse200 = {
  data: void;
  status: 200;
};

export type sessionControllerDeleteSessionResponse404 = {
  data: void;
  status: 404;
};

export type sessionControllerDeleteSessionResponse409 = {
  data: void;
  status: 409;
};

export type sessionControllerDeleteSessionResponseSuccess =
  sessionControllerDeleteSessionResponse200 & {
    headers: Headers;
  };
export type sessionControllerDeleteSessionResponseError = (
  | sessionControllerDeleteSessionResponse404
  | sessionControllerDeleteSessionResponse409
) & {
  headers: Headers;
};

export type sessionControllerDeleteSessionResponse =
  | sessionControllerDeleteSessionResponseSuccess
  | sessionControllerDeleteSessionResponseError;

export const getSessionControllerDeleteSessionUrl = (id: string) => {
  return `/sessions/${id}`;
};

export const sessionControllerDeleteSession = async (
  id: string,
  options?: RequestInit
): Promise<sessionControllerDeleteSessionResponse> => {
  return customInstance<sessionControllerDeleteSessionResponse>(
    getSessionControllerDeleteSessionUrl(id),
    {
      ...options,
      method: 'DELETE',
    }
  );
};

export const getSessionControllerDeleteSessionMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sessionControllerDeleteSession>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sessionControllerDeleteSession>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['sessionControllerDeleteSession'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sessionControllerDeleteSession>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return sessionControllerDeleteSession(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SessionControllerDeleteSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerDeleteSession>>
>;

export type SessionControllerDeleteSessionMutationError = void;

/**
 * @summary Delete a session
 */
export const useSessionControllerDeleteSession = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sessionControllerDeleteSession>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof sessionControllerDeleteSession>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getSessionControllerDeleteSessionMutationOptions(options), queryClient);
};
/**
 * @summary Close a session
 */
export type sessionControllerCloseSessionResponse200 = {
  data: void;
  status: 200;
};

export type sessionControllerCloseSessionResponse404 = {
  data: void;
  status: 404;
};

export type sessionControllerCloseSessionResponseSuccess =
  sessionControllerCloseSessionResponse200 & {
    headers: Headers;
  };
export type sessionControllerCloseSessionResponseError =
  sessionControllerCloseSessionResponse404 & {
    headers: Headers;
  };

export type sessionControllerCloseSessionResponse =
  | sessionControllerCloseSessionResponseSuccess
  | sessionControllerCloseSessionResponseError;

export const getSessionControllerCloseSessionUrl = (id: string) => {
  return `/sessions/${id}/close`;
};

export const sessionControllerCloseSession = async (
  id: string,
  options?: RequestInit
): Promise<sessionControllerCloseSessionResponse> => {
  return customInstance<sessionControllerCloseSessionResponse>(
    getSessionControllerCloseSessionUrl(id),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getSessionControllerCloseSessionMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sessionControllerCloseSession>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sessionControllerCloseSession>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['sessionControllerCloseSession'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sessionControllerCloseSession>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return sessionControllerCloseSession(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SessionControllerCloseSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerCloseSession>>
>;

export type SessionControllerCloseSessionMutationError = void;

/**
 * @summary Close a session
 */
export const useSessionControllerCloseSession = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sessionControllerCloseSession>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof sessionControllerCloseSession>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getSessionControllerCloseSessionMutationOptions(options), queryClient);
};
/**
 * @summary Send a message to the session
 */
export type sessionControllerSendMessageResponse201 = {
  data: void;
  status: 201;
};

export type sessionControllerSendMessageResponse404 = {
  data: void;
  status: 404;
};

export type sessionControllerSendMessageResponseSuccess =
  sessionControllerSendMessageResponse201 & {
    headers: Headers;
  };
export type sessionControllerSendMessageResponseError = sessionControllerSendMessageResponse404 & {
  headers: Headers;
};

export type sessionControllerSendMessageResponse =
  | sessionControllerSendMessageResponseSuccess
  | sessionControllerSendMessageResponseError;

export const getSessionControllerSendMessageUrl = (id: string) => {
  return `/sessions/${id}/messages`;
};

export const sessionControllerSendMessage = async (
  id: string,
  sendMessageDto: SendMessageDto,
  options?: RequestInit
): Promise<sessionControllerSendMessageResponse> => {
  return customInstance<sessionControllerSendMessageResponse>(
    getSessionControllerSendMessageUrl(id),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(sendMessageDto),
    }
  );
};

export const getSessionControllerSendMessageMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sessionControllerSendMessage>>,
    TError,
    { id: string; data: SendMessageDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sessionControllerSendMessage>>,
  TError,
  { id: string; data: SendMessageDto },
  TContext
> => {
  const mutationKey = ['sessionControllerSendMessage'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sessionControllerSendMessage>>,
    { id: string; data: SendMessageDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return sessionControllerSendMessage(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SessionControllerSendMessageMutationResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerSendMessage>>
>;
export type SessionControllerSendMessageMutationBody = SendMessageDto;
export type SessionControllerSendMessageMutationError = void;

/**
 * @summary Send a message to the session
 */
export const useSessionControllerSendMessage = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sessionControllerSendMessage>>,
      TError,
      { id: string; data: SendMessageDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof sessionControllerSendMessage>>,
  TError,
  { id: string; data: SendMessageDto },
  TContext
> => {
  return useMutation(getSessionControllerSendMessageMutationOptions(options), queryClient);
};
/**
 * @summary SSE stream for real-time updates
 */
export type sessionControllerStreamResponse200 = {
  data: void;
  status: 200;
};

export type sessionControllerStreamResponseSuccess = sessionControllerStreamResponse200 & {
  headers: Headers;
};
export type sessionControllerStreamResponse = sessionControllerStreamResponseSuccess;

export const getSessionControllerStreamUrl = (id: string) => {
  return `/sessions/${id}/stream`;
};

export const sessionControllerStream = async (
  id: string,
  options?: RequestInit
): Promise<sessionControllerStreamResponse> => {
  return customInstance<sessionControllerStreamResponse>(getSessionControllerStreamUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getSessionControllerStreamQueryKey = (id?: string) => {
  return [`/sessions/${id}/stream`] as const;
};

export const getSessionControllerStreamQueryOptions = <
  TData = Awaited<ReturnType<typeof sessionControllerStream>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionControllerStream>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSessionControllerStreamQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof sessionControllerStream>>> = ({
    signal,
  }) => sessionControllerStream(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof sessionControllerStream>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SessionControllerStreamQueryResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerStream>>
>;
export type SessionControllerStreamQueryError = unknown;

export function useSessionControllerStream<
  TData = Awaited<ReturnType<typeof sessionControllerStream>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionControllerStream>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerStream>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerStream>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSessionControllerStream<
  TData = Awaited<ReturnType<typeof sessionControllerStream>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionControllerStream>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionControllerStream>>,
          TError,
          Awaited<ReturnType<typeof sessionControllerStream>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSessionControllerStream<
  TData = Awaited<ReturnType<typeof sessionControllerStream>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionControllerStream>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary SSE stream for real-time updates
 */

export function useSessionControllerStream<
  TData = Awaited<ReturnType<typeof sessionControllerStream>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionControllerStream>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSessionControllerStreamQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Resolve a pending approval
 */
export type sessionControllerResolveApprovalResponse200 = {
  data: void;
  status: 200;
};

export type sessionControllerResolveApprovalResponse404 = {
  data: void;
  status: 404;
};

export type sessionControllerResolveApprovalResponseSuccess =
  sessionControllerResolveApprovalResponse200 & {
    headers: Headers;
  };
export type sessionControllerResolveApprovalResponseError =
  sessionControllerResolveApprovalResponse404 & {
    headers: Headers;
  };

export type sessionControllerResolveApprovalResponse =
  | sessionControllerResolveApprovalResponseSuccess
  | sessionControllerResolveApprovalResponseError;

export const getSessionControllerResolveApprovalUrl = (id: string, approvalId: string) => {
  return `/sessions/${id}/approvals/${approvalId}/resolve`;
};

export const sessionControllerResolveApproval = async (
  id: string,
  approvalId: string,
  resolveApprovalDto: ResolveApprovalDto,
  options?: RequestInit
): Promise<sessionControllerResolveApprovalResponse> => {
  return customInstance<sessionControllerResolveApprovalResponse>(
    getSessionControllerResolveApprovalUrl(id, approvalId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(resolveApprovalDto),
    }
  );
};

export const getSessionControllerResolveApprovalMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sessionControllerResolveApproval>>,
    TError,
    { id: string; approvalId: string; data: ResolveApprovalDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sessionControllerResolveApproval>>,
  TError,
  { id: string; approvalId: string; data: ResolveApprovalDto },
  TContext
> => {
  const mutationKey = ['sessionControllerResolveApproval'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sessionControllerResolveApproval>>,
    { id: string; approvalId: string; data: ResolveApprovalDto }
  > = (props) => {
    const { id, approvalId, data } = props ?? {};

    return sessionControllerResolveApproval(id, approvalId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SessionControllerResolveApprovalMutationResult = NonNullable<
  Awaited<ReturnType<typeof sessionControllerResolveApproval>>
>;
export type SessionControllerResolveApprovalMutationBody = ResolveApprovalDto;
export type SessionControllerResolveApprovalMutationError = void;

/**
 * @summary Resolve a pending approval
 */
export const useSessionControllerResolveApproval = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sessionControllerResolveApproval>>,
      TError,
      { id: string; approvalId: string; data: ResolveApprovalDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof sessionControllerResolveApproval>>,
  TError,
  { id: string; approvalId: string; data: ResolveApprovalDto },
  TContext
> => {
  return useMutation(getSessionControllerResolveApprovalMutationOptions(options), queryClient);
};
