/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Gourmet7 Agent API
 * AI Agent for DeFi operations
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateWalletDto,
  WalletAssetsResponseDto,
  WalletControllerDelete200,
  WalletControllerFindAllParams,
  WalletControllerGetAssetsParams,
  WalletListResponseDto,
  WalletResponseDto,
} from '../../schemas';

import { customInstance } from '../../axios-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Creates a DEV wallet with private key stored in database. For local development only!
 * @summary Create a new wallet
 */
export type walletControllerCreateResponse201 = {
  data: WalletResponseDto;
  status: 201;
};

export type walletControllerCreateResponse409 = {
  data: void;
  status: 409;
};

export type walletControllerCreateResponseSuccess = walletControllerCreateResponse201 & {
  headers: Headers;
};
export type walletControllerCreateResponseError = walletControllerCreateResponse409 & {
  headers: Headers;
};

export type walletControllerCreateResponse =
  | walletControllerCreateResponseSuccess
  | walletControllerCreateResponseError;

export const getWalletControllerCreateUrl = () => {
  return `/wallets`;
};

export const walletControllerCreate = async (
  createWalletDto: CreateWalletDto,
  options?: RequestInit
): Promise<walletControllerCreateResponse> => {
  return customInstance<walletControllerCreateResponse>(getWalletControllerCreateUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createWalletDto),
  });
};

export const getWalletControllerCreateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof walletControllerCreate>>,
    TError,
    { data: CreateWalletDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof walletControllerCreate>>,
  TError,
  { data: CreateWalletDto },
  TContext
> => {
  const mutationKey = ['walletControllerCreate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof walletControllerCreate>>,
    { data: CreateWalletDto }
  > = (props) => {
    const { data } = props ?? {};

    return walletControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type WalletControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof walletControllerCreate>>
>;
export type WalletControllerCreateMutationBody = CreateWalletDto;
export type WalletControllerCreateMutationError = void;

/**
 * @summary Create a new wallet
 */
export const useWalletControllerCreate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof walletControllerCreate>>,
      TError,
      { data: CreateWalletDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof walletControllerCreate>>,
  TError,
  { data: CreateWalletDto },
  TContext
> => {
  return useMutation(getWalletControllerCreateMutationOptions(options), queryClient);
};
/**
 * Returns paginated list of wallets owned by the current user
 * @summary List user wallets
 */
export type walletControllerFindAllResponse200 = {
  data: WalletListResponseDto;
  status: 200;
};

export type walletControllerFindAllResponseSuccess = walletControllerFindAllResponse200 & {
  headers: Headers;
};
export type walletControllerFindAllResponse = walletControllerFindAllResponseSuccess;

export const getWalletControllerFindAllUrl = (params?: WalletControllerFindAllParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/wallets?${stringifiedParams}` : `/wallets`;
};

export const walletControllerFindAll = async (
  params?: WalletControllerFindAllParams,
  options?: RequestInit
): Promise<walletControllerFindAllResponse> => {
  return customInstance<walletControllerFindAllResponse>(getWalletControllerFindAllUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getWalletControllerFindAllQueryKey = (params?: WalletControllerFindAllParams) => {
  return [`/wallets`, ...(params ? [params] : [])] as const;
};

export const getWalletControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof walletControllerFindAll>>,
  TError = unknown,
>(
  params?: WalletControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof walletControllerFindAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getWalletControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof walletControllerFindAll>>> = ({
    signal,
  }) => walletControllerFindAll(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof walletControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type WalletControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof walletControllerFindAll>>
>;
export type WalletControllerFindAllQueryError = unknown;

export function useWalletControllerFindAll<
  TData = Awaited<ReturnType<typeof walletControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | WalletControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof walletControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof walletControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof walletControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useWalletControllerFindAll<
  TData = Awaited<ReturnType<typeof walletControllerFindAll>>,
  TError = unknown,
>(
  params?: WalletControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof walletControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof walletControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof walletControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useWalletControllerFindAll<
  TData = Awaited<ReturnType<typeof walletControllerFindAll>>,
  TError = unknown,
>(
  params?: WalletControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof walletControllerFindAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List user wallets
 */

export function useWalletControllerFindAll<
  TData = Awaited<ReturnType<typeof walletControllerFindAll>>,
  TError = unknown,
>(
  params?: WalletControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof walletControllerFindAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getWalletControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns wallet details (without private key)
 * @summary Get wallet by ID
 */
export type walletControllerFindOneResponse200 = {
  data: WalletResponseDto;
  status: 200;
};

export type walletControllerFindOneResponse403 = {
  data: void;
  status: 403;
};

export type walletControllerFindOneResponse404 = {
  data: void;
  status: 404;
};

export type walletControllerFindOneResponseSuccess = walletControllerFindOneResponse200 & {
  headers: Headers;
};
export type walletControllerFindOneResponseError = (
  | walletControllerFindOneResponse403
  | walletControllerFindOneResponse404
) & {
  headers: Headers;
};

export type walletControllerFindOneResponse =
  | walletControllerFindOneResponseSuccess
  | walletControllerFindOneResponseError;

export const getWalletControllerFindOneUrl = (id: string) => {
  return `/wallets/${id}`;
};

export const walletControllerFindOne = async (
  id: string,
  options?: RequestInit
): Promise<walletControllerFindOneResponse> => {
  return customInstance<walletControllerFindOneResponse>(getWalletControllerFindOneUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getWalletControllerFindOneQueryKey = (id?: string) => {
  return [`/wallets/${id}`] as const;
};

export const getWalletControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof walletControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof walletControllerFindOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getWalletControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof walletControllerFindOne>>> = ({
    signal,
  }) => walletControllerFindOne(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof walletControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type WalletControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof walletControllerFindOne>>
>;
export type WalletControllerFindOneQueryError = void;

export function useWalletControllerFindOne<
  TData = Awaited<ReturnType<typeof walletControllerFindOne>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof walletControllerFindOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof walletControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof walletControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useWalletControllerFindOne<
  TData = Awaited<ReturnType<typeof walletControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof walletControllerFindOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof walletControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof walletControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useWalletControllerFindOne<
  TData = Awaited<ReturnType<typeof walletControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof walletControllerFindOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get wallet by ID
 */

export function useWalletControllerFindOne<
  TData = Awaited<ReturnType<typeof walletControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof walletControllerFindOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getWalletControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Permanently deletes a wallet. Cannot delete wallets assigned to agents.
 * @summary Delete wallet
 */
export type walletControllerDeleteResponse200 = {
  data: WalletControllerDelete200;
  status: 200;
};

export type walletControllerDeleteResponse403 = {
  data: void;
  status: 403;
};

export type walletControllerDeleteResponse404 = {
  data: void;
  status: 404;
};

export type walletControllerDeleteResponse409 = {
  data: void;
  status: 409;
};

export type walletControllerDeleteResponseSuccess = walletControllerDeleteResponse200 & {
  headers: Headers;
};
export type walletControllerDeleteResponseError = (
  | walletControllerDeleteResponse403
  | walletControllerDeleteResponse404
  | walletControllerDeleteResponse409
) & {
  headers: Headers;
};

export type walletControllerDeleteResponse =
  | walletControllerDeleteResponseSuccess
  | walletControllerDeleteResponseError;

export const getWalletControllerDeleteUrl = (id: string) => {
  return `/wallets/${id}`;
};

export const walletControllerDelete = async (
  id: string,
  options?: RequestInit
): Promise<walletControllerDeleteResponse> => {
  return customInstance<walletControllerDeleteResponse>(getWalletControllerDeleteUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getWalletControllerDeleteMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof walletControllerDelete>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof walletControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['walletControllerDelete'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof walletControllerDelete>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return walletControllerDelete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type WalletControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof walletControllerDelete>>
>;

export type WalletControllerDeleteMutationError = void;

/**
 * @summary Delete wallet
 */
export const useWalletControllerDelete = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof walletControllerDelete>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof walletControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getWalletControllerDeleteMutationOptions(options), queryClient);
};
/**
 * Returns token balances for the wallet on the specified network
 * @summary Get wallet assets
 */
export type walletControllerGetAssetsResponse200 = {
  data: WalletAssetsResponseDto;
  status: 200;
};

export type walletControllerGetAssetsResponse404 = {
  data: void;
  status: 404;
};

export type walletControllerGetAssetsResponseSuccess = walletControllerGetAssetsResponse200 & {
  headers: Headers;
};
export type walletControllerGetAssetsResponseError = walletControllerGetAssetsResponse404 & {
  headers: Headers;
};

export type walletControllerGetAssetsResponse =
  | walletControllerGetAssetsResponseSuccess
  | walletControllerGetAssetsResponseError;

export const getWalletControllerGetAssetsUrl = (
  id: string,
  params?: WalletControllerGetAssetsParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/wallets/${id}/assets?${stringifiedParams}`
    : `/wallets/${id}/assets`;
};

export const walletControllerGetAssets = async (
  id: string,
  params?: WalletControllerGetAssetsParams,
  options?: RequestInit
): Promise<walletControllerGetAssetsResponse> => {
  return customInstance<walletControllerGetAssetsResponse>(
    getWalletControllerGetAssetsUrl(id, params),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getWalletControllerGetAssetsQueryKey = (
  id?: string,
  params?: WalletControllerGetAssetsParams
) => {
  return [`/wallets/${id}/assets`, ...(params ? [params] : [])] as const;
};

export const getWalletControllerGetAssetsQueryOptions = <
  TData = Awaited<ReturnType<typeof walletControllerGetAssets>>,
  TError = void,
>(
  id: string,
  params?: WalletControllerGetAssetsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof walletControllerGetAssets>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getWalletControllerGetAssetsQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof walletControllerGetAssets>>> = ({
    signal,
  }) => walletControllerGetAssets(id, params, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof walletControllerGetAssets>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type WalletControllerGetAssetsQueryResult = NonNullable<
  Awaited<ReturnType<typeof walletControllerGetAssets>>
>;
export type WalletControllerGetAssetsQueryError = void;

export function useWalletControllerGetAssets<
  TData = Awaited<ReturnType<typeof walletControllerGetAssets>>,
  TError = void,
>(
  id: string,
  params: undefined | WalletControllerGetAssetsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof walletControllerGetAssets>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof walletControllerGetAssets>>,
          TError,
          Awaited<ReturnType<typeof walletControllerGetAssets>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useWalletControllerGetAssets<
  TData = Awaited<ReturnType<typeof walletControllerGetAssets>>,
  TError = void,
>(
  id: string,
  params?: WalletControllerGetAssetsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof walletControllerGetAssets>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof walletControllerGetAssets>>,
          TError,
          Awaited<ReturnType<typeof walletControllerGetAssets>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useWalletControllerGetAssets<
  TData = Awaited<ReturnType<typeof walletControllerGetAssets>>,
  TError = void,
>(
  id: string,
  params?: WalletControllerGetAssetsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof walletControllerGetAssets>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get wallet assets
 */

export function useWalletControllerGetAssets<
  TData = Awaited<ReturnType<typeof walletControllerGetAssets>>,
  TError = void,
>(
  id: string,
  params?: WalletControllerGetAssetsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof walletControllerGetAssets>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getWalletControllerGetAssetsQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
